apiVersion: v1
kind: Service
metadata:
  name: prometheuslb
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheusweb
      port: 9090
      targetPort: web
  type: LoadBalancer